DATA = {
    "uk": [
        ("Як залучити більше трафіку на казино?", "Використовуйте SEO, контекстну рекламу та партнерські програми."),
        ("Які ГЕО найкращі для казино?", "Залежить від продукту, але популярні: UA, RU, IN, BR."),
        ("Як уникнути бану в Google Ads?", "Дотримуйтесь правил, використовуйте клоакінг обережно."),
        ("Які джерела трафіку найефективніші?", "Пошуковий трафік, соціальні мережі, email-маркетинг."),
        ("Як оптимізувати рекламні кампанії?", "Тестуйте різні креативи, аналізуйте ROI, використовуйте A/B-тестування."),
        ("Що таке клоакінг і як його використовувати?", "Клоакінг — це приховування реального контенту від модераторів. Використовуйте з обережністю."),
        ("Як працювати з партнерськими програмами?", "Оберіть надійних партнерів, домовляйтесь про вигідні умови."),
        ("Які інструменти для відстеження трафіку?", "Google Analytics, трекери типу Keitaro або Binom."),
        ("Як залучити трафік з соціальних мереж?", "Створюйте привабливий контент, використовуйте таргетовану рекламу."),
        ("Які помилки найчастіше роблять новачки?", "Неправильний вибір ГЕО, погана оптимізація кампаній, ігнорування аналітики."),
        ("Як обрати казино для просування?", "Дивіться на репутацію, відгуки, умови партнерської програми."),
        ("Що таке ревшара і CPA?", "Ревшара — відсоток від доходу, CPA — фіксована оплата за дію."),
        ("Як залучити трафік з YouTube?", "Створюйте огляди, стріми, навчальні відео про казино."),
        ("Які креативи найкраще працюють?", "Залежить від аудиторії, але часто — бонуси, акції, виграші."),
        ("Як працювати з email-маркетингом?", "Збирайте базу підписників, надсилайте персоналізовані пропозиції."),
        ("Що таке SEO для казино?", "Оптимізація сайту для пошукових систем з фокусом на ключові слова."),
        ("Як уникнути фроду в трафіку?", "Використовуйте антифрод-системи, перевіряйте джерела трафіку."),
        ("Які метрики важливі для аналізу?", "CTR, CR, EPC, ROI, LTV."),
        ("Як залучити трафік з Telegram?", "Створюйте канали з новинами, акціями, бонусами."),
        ("Що таке арбітраж трафіку?", "Купівля трафіку з одного джерела і продаж на інше з прибутком."),
        ("Як працювати з Push-рекламою?", "Створюйте привабливі повідомлення, тестуйте різні формати."),
        ("Які ГЕО мають високий LTV?", "Зазвичай Tier-1 країни: США, Канада, Австралія."),
        ("Як залучити трафік з форумів?", "Беріть участь у дискусіях, пропонуйте корисний контент."),
        ("Що таке контекстна реклама?", "Реклама, що показується на основі пошукових запитів користувача."),
        ("Як працювати з інфлюенсерами?", "Співпрацюйте з блогерами, які мають аудиторію, зацікавлену в азартних іграх."),
        ("Які ризики при роботі з казино?", "Юридичні обмеження, проблеми з виплатами, конкуренція."),
        ("Як залучити трафік з TikTok?", "Створюйте короткі відео з акціями, виграшами, челенджами."),
        ("Що таке PPC-реклама?", "Оплата за клік, популярна в Google Ads, Bing Ads."),
        ("Як оптимізувати лендінги?", "Використовуйте A/B-тестування, покращуйте юзабіліті, додавайте заклики до дії."),
        ("Які інструменти для автоматизації?", "Трекери, боти для соціальних мереж, CRM-системи."),
        ("Як працювати з мобільним трафіком?", "Оптимізуйте сайти для мобільних пристроїв, використовуйте мобільні додатки."),
        ("Що таке programmatic advertising?", "Автоматизована купівля реклами через платформи."),
        ("Як залучити трафік з Reddit?", "Беріть участь у сабредітах, пов'язаних з азартними іграми."),
        ("Які креативи заборонені?", "Зазвичай — оманливі обіцянки, контент для дорослих, порушення авторських прав."),
        ("Як працювати з CPA-мережами?", "Реєструйтесь, обирайте офери, запускайте кампанії."),
        ("Що таке ретаргетинг?", "Показ реклами користувачам, які вже відвідували ваш сайт."),
        ("Як залучити трафік з Instagram?", "Використовуйте Stories, Reels, співпрацюйте з інфлюенсерами."),
        ("Які ГЕО мають низький CPM?", "Зазвичай Tier-3 країни: Індія, Філіппіни, В'єтнам."),
        ("Як працювати з банерною рекламою?", "Створюйте привабливі банери, розміщуйте на тематичних сайтах."),
        ("Що таке affiliate marketing?", "Партнерський маркетинг, де ви отримуєте комісію за залучених гравців."),
        ("Як залучити трафік з Pinterest?", "Створюйте привабливі піни з акціями та бонусами."),
        ("Які інструменти для аналізу конкурентів?", "SEMrush, Ahrefs, SimilarWeb."),
        ("Як працювати з відеоконтентом?", "Створюйте огляди, стріми, навчальні відео."),
        ("Що таке нативна реклама?", "Реклама, що виглядає як органічний контент."),
        ("Як залучити трафік з Twitter?", "Публікуйте твіти з акціями, використовуйте хештеги."),
        ("Які ГЕО мають високий ARPU?", "Tier-1 країни, наприклад, Норвегія, Швеція, Німеччина."),
        ("Як працювати з SMS-маркетингом?", "Надсилайте персоналізовані повідомлення з акціями."),
        ("Що таке programmatic direct?", "Пряма купівля реклами через programmatic-платформи."),
        ("Як залучити трафік з LinkedIn?", "Публікуйте статті, беріть участь у групах, пов'язаних з азартними іграми."),
        ("Які креативи найкраще працюють для мобільних пристроїв?", "Адаптивні банери, відео, інтерактивні елементи."),
    ],
    "ru": [
        ("Как привлечь больше трафика на казино?", "Используйте SEO, контекстную рекламу и партнерские программы."),
        ("Какие ГЕО лучшие для казино?", "Зависит от продукта, но популярны: UA, RU, IN, BR."),
        ("Как избежать бана в Google Ads?", "Соблюдайте правила, аккуратно используйте клоакинг."),
        ("Какие источники трафика самые эффективные?", "Поисковый трафик, социальные сети, email-маркетинг."),
        ("Как оптимизировать рекламные кампании?", "Тестируйте разные креативы, анализируйте ROI, используйте A/B-тестирование."),
        ("Что такое клоакинг и как его использовать?", "Клоакинг — скрытие реального контента от модераторов. Используйте осторожно."),
        ("Как работать с партнерскими программами?", "Выбирайте надежных партнеров, договаривайтесь о выгодных условиях."),
        ("Какие инструменты для отслеживания трафика?", "Google Analytics, трекеры типа Keitaro или Binom."),
        ("Как привлечь трафик из социальных сетей?", "Создавайте привлекательный контент, используйте таргетированную рекламу."),
        ("Какие ошибки чаще всего делают новички?", "Неправильный выбор ГЕО, плохая оптимизация кампаний, игнорирование аналитики."),
        ("Как выбрать казино для продвижения?", "Смотрите на репутацию, отзывы, условия партнерской программы."),
        ("Что такое ревшара и CPA?", "Ревшара — процент от дохода, CPA — фиксированная оплата за действие."),
        ("Как привлечь трафик с YouTube?", "Создавайте обзоры, стримы, обучающие видео о казино."),
        ("Какие креативы лучше всего работают?", "Зависит от аудитории, но часто — бонусы, акции, выигрыши."),
        ("Как работать с email-маркетингом?", "Собирайте базу подписчиков, отправляйте персонализированные предложения."),
        ("Что такое SEO для казино?", "Оптимизация сайта для поисковых систем с фокусом на ключевые слова."),
        ("Как избежать фрода в трафике?", "Используйте антифрод-системы, проверяйте источники трафика."),
        ("Какие метрики важны для анализа?", "CTR, CR, EPC, ROI, LTV."),
        ("Как привлечь трафик с Telegram?", "Создавайте каналы с новостями, акциями, бонусами."),
        ("Что такое арбитраж трафика?", "Покупка трафика с одного источника и продажа на другой с прибылью."),
        ("Как работать с Push-рекламой?", "Создавайте привлекательные сообщения, тестируйте разные форматы."),
        ("Какие ГЕО имеют высокий LTV?", "Обычно Tier-1 страны: США, Канада, Австралия."),
        ("Как привлечь трафик с форумов?", "Участвуйте в дискуссиях, предлагайте полезный контент."),
        ("Что такое контекстная реклама?", "Реклама, показываемая на основе поисковых запросов пользователя."),
        ("Как работать с инфлюенсерами?", "Сотрудничайте с блогерами, у которых есть аудитория, интересующаяся азартными играми."),
        ("Какие риски при работе с казино?", "Юридические ограничения, проблемы с выплатами, конкуренция."),
        ("Как привлечь трафик с TikTok?", "Создавайте короткие видео с акциями, выигрышами, челленджами."),
        ("Что такое PPC-реклама?", "Оплата за клик, популярна в Google Ads, Bing Ads."),
        ("Как оптимизировать лендинги?", "Используйте A/B-тестирование, улучшайте юзабилити, добавляйте призывы к действию."),
        ("Какие инструменты для автоматизации?", "Трекеры, боты для социальных сетей, CRM-системы."),
        ("Как работать с мобильным трафиком?", "Оптимизируйте сайты для мобильных устройств, используйте мобильные приложения."),
        ("Что такое programmatic advertising?", "Автоматизированная покупка рекламы через платформы."),
        ("Как привлечь трафик с Reddit?", "Участвуйте в сабреддитах, связанных с азартными играми."),
        ("Какие креативы запрещены?", "Обычно — обманчивые обещания, контент для взрослых, нарушение авторских прав."),
        ("Как работать с CPA-сетями?", "Регистрируйтесь, выбирайте офферы, запускайте кампании."),
        ("Что такое ретаргетинг?", "Показ рекламы пользователям, которые уже посещали ваш сайт."),
        ("Как привлечь трафик с Instagram?", "Используйте Stories, Reels, сотрудничайте с инфлюенсерами."),
        ("Какие ГЕО имеют низкий CPM?", "Обычно Tier-3 страны: Индия, Филиппины, Вьетнам."),
        ("Как работать с баннерной рекламой?", "Создавайте привлекательные баннеры, размещайте на тематических сайтах."),
        ("Что такое affiliate marketing?", "Партнерский маркетинг, где вы получаете комиссию за привлеченных игроков."),
        ("Как привлечь трафик с Pinterest?", "Создавайте привлекательные пины с акциями и бонусами."),
        ("Какие инструменты для анализа конкурентов?", "SEMrush, Ahrefs, SimilarWeb."),
        ("Как работать с видеоконтентом?", "Создавайте обзоры, стримы, обучающие видео."),
        ("Что такое нативная реклама?", "Реклама, которая выглядит как органический контент."),
        ("Как привлечь трафик с Twitter?", "Публикуйте твиты с акциями, используйте хэштеги."),
        ("Какие ГЕО имеют высокий ARPU?", "Tier-1 страны, например, Норвегия, Швеция, Германия."),
        ("Как работать с SMS-маркетингом?", "Отправляйте персонализированные сообщения с акциями."),
        ("Что такое programmatic direct?", "Прямая покупка рекламы через programmatic-платформы."),
        ("Как привлечь трафик с LinkedIn?", "Публикуйте статьи, участвуйте в группах, связанных с азартными играми."),
        ("Какие креативы лучше всего работают для мобильных устройств?", "Адаптивные баннеры, видео, интерактивные элементы."),
    ],
    "en": [
        ("How to drive more traffic to a casino?", "Use SEO, PPC ads, and affiliate programs."),
        ("Which GEOs are best for casinos?", "Depends on the product, but popular ones are: UA, RU, IN, BR."),
        ("How to avoid a Google Ads ban?", "Follow policies, use cloaking carefully."),
        ("What are the most effective traffic sources?", "Search traffic, social media, email marketing."),
        ("How to optimize ad campaigns?", "Test different creatives, analyze ROI, use A/B testing."),
        ("What is cloaking and how to use it?", "Cloaking hides real content from moderators. Use it cautiously."),
        ("How to work with affiliate programs?", "Choose reliable partners, negotiate favorable terms."),
        ("What tools to track traffic?", "Google Analytics, trackers like Keitaro or Binom."),
        ("How to drive traffic from social media?", "Create engaging content, use targeted ads."),
        ("What are common newbie mistakes?", "Wrong GEO choice, poor campaign optimization, ignoring analytics."),
        ("How to choose a casino to promote?", "Look at reputation, reviews, affiliate program terms."),
        ("What are revshare and CPA?", "Revshare is a percentage of revenue, CPA is a fixed payment per action."),
        ("How to drive traffic from YouTube?", "Create reviews, streams, educational videos about casinos."),
        ("Which creatives work best?", "Depends on the audience, but often bonuses, promotions, winnings."),
        ("How to work with email marketing?", "Build a subscriber list, send personalized offers."),
        ("What is SEO for casinos?", "Optimizing the site for search engines with a focus on keywords."),
        ("How to avoid fraud in traffic?", "Use anti-fraud systems, check traffic sources."),
        ("What metrics are important for analysis?", "CTR, CR, EPC, ROI, LTV."),
        ("How to drive traffic from Telegram?", "Create channels with news, promotions, bonuses."),
        ("What is traffic arbitrage?", "Buying traffic from one source and selling to another for profit."),
        ("How to work with Push ads?", "Create compelling messages, test different formats."),
        ("Which GEOs have high LTV?", "Usually Tier-1 countries: USA, Canada, Australia."),
        ("How to drive traffic from forums?", "Participate in discussions, offer valuable content."),
        ("What is contextual advertising?", "Ads shown based on user search queries."),
        ("How to work with influencers?", "Collaborate with bloggers who have an audience interested in gambling."),
        ("What are the risks when working with casinos?", "Legal restrictions, payment issues, competition."),
        ("How to drive traffic from TikTok?", "Create short videos with promotions, winnings, challenges."),
        ("What is PPC advertising?", "Pay-per-click, popular in Google Ads, Bing Ads."),
        ("How to optimize landing pages?", "Use A/B testing, improve usability, add calls to action."),
        ("What tools for automation?", "Trackers, social media bots, CRM systems."),
        ("How to work with mobile traffic?", "Optimize sites for mobile devices, use mobile apps."),
        ("What is programmatic advertising?", "Automated ad buying through platforms."),
        ("How to drive traffic from Reddit?", "Participate in gambling-related subreddits."),
        ("Which creatives are banned?", "Usually misleading claims, adult content, copyright violations."),
        ("How to work with CPA networks?", "Register, choose offers, launch campaigns."),
        ("What is retargeting?", "Showing ads to users who have already visited your site."),
        ("How to drive traffic from Instagram?", "Use Stories, Reels, collaborate with influencers."),
        ("Which GEOs have low CPM?", "Usually Tier-3 countries: India, Philippines, Vietnam."),
        ("How to work with banner ads?", "Create attractive banners, place them on thematic sites."),
        ("What is affiliate marketing?", "Partner marketing where you earn commissions for referred players."),
        ("How to drive traffic from Pinterest?", "Create appealing pins with promotions and bonuses."),
        ("What tools to analyze competitors?", "SEMrush, Ahrefs, SimilarWeb."),
        ("How to work with video content?", "Create reviews, streams, educational videos."),
        ("What is native advertising?", "Ads that look like organic content."),
        ("How to drive traffic from Twitter?", "Post tweets with promotions, use hashtags."),
        ("Which GEOs have high ARPU?", "Tier-1 countries like Norway, Sweden, Germany."),
        ("How to work with SMS marketing?", "Send personalized messages with promotions."),
        ("What is programmatic direct?", "Direct ad buying through programmatic platforms."),
        ("How to drive traffic from LinkedIn?", "Publish articles, participate in gambling-related groups."),
        ("Which creatives work best for mobile devices?", "Responsive banners, videos, interactive elements."),
    ],
}